# # Datos
# VENTAS_DIARIAS
# DEMORA_PROVEEDOR
# DESPERFECTO_EQUIPO_DE_EMPAQUETADO
# AUSENCIA_EMPREADOS
# PESTE_EN_STOCK
#
# # Control
# STOCK_AVENA
# CANT_OPERARIOS
#
# # Resultados
# PROMEDIO_ANUAL_DE_VENTAS
# PORCENTAJE_VENTAS_PERDIDAS
# PORCENTAJE_DE_PERDIDA_DEL_STOCK_POR_PESTE
# BENEFICIO
#
# # Estado
# STOCK_AVENA
# STOCK_AVENA_EMPAQUETADA
#
# # TEF
# FECHA_LLEGADA_PEDIDO


def main():
    print("Hello from quater-oat!")


if __name__ == "__main__":
    main()
